Remove Meta, Change UniModule order
Comment Out Meta because it is causing error,
`export function getDOM() {
^^^^^^
SyntaxError: Unexpected token export
`
 Change Order of UniversalModule loading to be after MaterialModule to stop Error
`EXCEPTION: Uncaught (in promise): Error: This method is not implemented in Parse5DomAdapter: getCookie`